services:
  mpi-node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mpi-node1
    hostname: mpi-node1
    command: /usr/sbin/sshd -D
    networks:
      mpi-net:
        ipv4_address: 172.30.0.2

  mpi-node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mpi-node2
    hostname: mpi-node2
    command: /usr/sbin/sshd -D
    networks:
      mpi-net:
        ipv4_address: 172.30.0.3

  mpi-node3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mpi-node3
    hostname: mpi-node3
    command: /usr/sbin/sshd -D
    networks:
      mpi-net:
        ipv4_address: 172.30.0.4

  mpi-node4:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mpi-node4
    hostname: mpi-node4
    command: /usr/sbin/sshd -D
    networks:
      mpi-net:
        ipv4_address: 172.30.0.5

networks:
  mpi-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
